// graph/styles.ts — all CSSProperties for the graph UI

import type { CSSProperties } from 'react';

const styles: Record<string, CSSProperties> = {
  progressWrap: {
    position: 'absolute',
    bottom: 60,
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'rgba(8,12,20,0.85)',
    border: '1px solid rgba(76,201,240,0.3)',
    borderRadius: 8,
    padding: '10px 16px',
    minWidth: 260,
    backdropFilter: 'blur(8px)',
  },
  progressLabel: {
    color: '#4cc9f0',
    fontSize: 12,
    fontFamily: 'monospace',
    marginBottom: 6,
  },
  progressTrack: {
    height: 4,
    borderRadius: 2,
    background: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    background: 'linear-gradient(90deg,#4361ee,#4cc9f0)',
    transition: 'width 0.2s ease',
    borderRadius: 2,
  },
  stats: {
    position: 'absolute',
    top: 16,
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: 20,
    background: 'rgba(8,12,20,0.75)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 20,
    padding: '6px 18px',
    backdropFilter: 'blur(10px)',
  },
  statItem: {
    color: '#c0d0e8',
    fontSize: 12,
    fontFamily: 'monospace',
    display: 'flex',
    alignItems: 'center',
  },
  panel: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 300,
    maxHeight: 'calc(100% - 32px)',
    overflowY: 'auto',
    background: 'rgba(8,12,20,0.92)',
    border: '1px solid rgba(76,201,240,0.25)',
    borderRadius: 12,
    padding: '18px 20px',
    backdropFilter: 'blur(16px)',
    color: '#e0eaf8',
    fontFamily: 'monospace',
  },
  panelClose: {
    position: 'absolute',
    top: 12,
    right: 12,
    background: 'transparent',
    border: 'none',
    color: '#6080a0',
    cursor: 'pointer',
    fontSize: 14,
  },
  panelType: {
    fontSize: 10,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  panelTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#e8f4ff',
    marginBottom: 4,
    wordBreak: 'break-word',
  },
  panelMeta: {
    fontSize: 11,
    color: '#5a7a9a',
    marginBottom: 2,
    wordBreak: 'break-word',
  },
  panelDivider: {
    height: 1,
    background: 'rgba(255,255,255,0.07)',
    margin: '12px 0',
  },
  panelSectionTitle: {
    fontSize: 11,
    color: '#4cc9f0',
    letterSpacing: '0.1em',
    marginBottom: 8,
  },
  neighbourList: { display: 'flex', flexDirection: 'column', gap: 4 },
  neighbourRow: { display: 'flex', alignItems: 'center', gap: 6 },
  neighbourDir: { color: '#7209b7', fontSize: 12, minWidth: 16 },
  neighbourRel: {
    fontSize: 10,
    color: '#3a6080',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: 4,
    padding: '1px 5px',
    minWidth: 60,
  },
  neighbourLabel: {
    fontSize: 11,
    color: '#a0c0d8',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: 160,
  },
  tooltip: {
    position: 'absolute',
    bottom: 100,
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'rgba(8,12,20,0.9)',
    border: '1px solid rgba(76,201,240,0.2)',
    borderRadius: 6,
    padding: '5px 12px',
    color: '#c0d8f0',
    fontSize: 12,
    fontFamily: 'monospace',
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
  },
  legend: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    background: 'rgba(8,12,20,0.7)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 8,
    padding: '10px 14px',
    backdropFilter: 'blur(8px)',
  },
  legendLabel: { color: '#6a90b0', fontSize: 11, fontFamily: 'monospace' },
  controls: {
    position: 'absolute',
    bottom: 16,
    left: '50%',
    transform: 'translateX(-50%)',
    color: 'rgba(100,140,180,0.6)',
    fontSize: 11,
    fontFamily: 'monospace',
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
  },
};

export { styles };
