import fs from 'fs/promises';
import path from 'path';
import { z } from 'zod';

async function main() {
  // graphify-out is located at repo root; when run from this package, go up two levels
  const inPath = path.resolve(process.cwd(), '..', '..', 'graphify-out', 'graph.json');
  let raw;
  try {
    raw = await fs.readFile(inPath, 'utf-8');
  } catch (err) {
    console.error('Could not read', inPath, err);
    process.exit(1);
  }

  let json;
  try {
    json = JSON.parse(raw);
  } catch (err) {
    console.error('Invalid JSON in', inPath, err);
    process.exit(1);
  }

  const NodeSchema = z.object({
    id: z.preprocess((v) => String(v), z.string()),
    label: z.string().optional(),
    ft: z.string().nullable().optional(),
    c: z.union([z.number(), z.string()]).nullable().optional(),
    sf: z.string().nullable().optional(),
  });

  const LinkSchema = z.object({
    s: z.preprocess((v) => String(v), z.string()),
    t: z.preprocess((v) => String(v), z.string()),
    r: z.string().nullable().optional(),
    w: z.number().optional().transform((v) => v ?? 1),
  });

  const HyperSchema = z.object({
    nodes: z.array(z.preprocess((v) => String(v), z.string())),
  }).partial();

  const GraphSchema = z.object({
    nodes: z.array(NodeSchema),
    links: z.array(LinkSchema),
    hyperedges: z.array(HyperSchema).optional(),
  });

  const parsed = GraphSchema.safeParse(json);
  if (!parsed.success) {
    console.error('graph.json failed validation:');
    console.error(parsed.error.format());
    process.exit(2);
  }

  const data = parsed.data;

  const outDir = path.resolve(process.cwd(), 'src', 'generated');
  await fs.mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, 'graph.ts');

  const fileContent = `/* This file is generated by apps/playground/scripts/generate-graph.mjs — do not edit */\n\nconst graphData = ${JSON.stringify(data, null, 2)} as const;\n\nexport default graphData;\n`;

  await fs.writeFile(outFile, fileContent, 'utf-8');
  console.log('Wrote', outFile);
}

main();
