name: Deploy to GitHub Pages

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache turbo build setup
        uses: actions/cache@v5
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Cache node_modules
        uses: actions/cache@v5
        with:
          path: |
            node_modules
            .pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Dependencies
        run: nix develop --command pnpm install

      - name: Type-check
        run: nix develop --command pnpm check-types

      - name: Lint
        run: nix develop --command pnpm lint

      - name: Build
        run: nix develop --command pnpm build

      - name: Verify storybook build exists
        run: |
          if [ ! -d "./apps/storybook/storybook-static" ]; then
            echo "Error: storybook-static not found" && exit 1
          fi
          if [ -z "$(ls -A ./apps/storybook/storybook-static)" ]; then
            echo "Error: storybook-static is empty" && exit 1
          fi

      - name: Merge storybook into Astro Dist
        run: |
          mkdir -p ./apps/playground/dist/storybook
          cp -r ./apps/storybook/storybook-static/. ./apps/playground/dist/storybook/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./apps/playground/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
